apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: zenml-workspaces
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/webHexer/gitops.git
        revision: HEAD
        directories:
          - path: workspaces/*

  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/webHexer/gitops.git
        targetRevision: HEAD
        path: zenml-chart
        helm:
          valueFiles:
            - ../workspaces/{{path.basename}}/values.yaml 

      destination:
        server: https://kubernetes.default.svc
        namespace: zenml

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true