apiVersion: v1
kind: Service
metadata:
  name: zenml
spec:
  selector:
    app: zenml
    workspace: {{ .Values.workspace }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP