
        apiVersion: v2
        name: zenml-raj-platform
        version: 0.1.0

        dependencies:
        - name: zenml
            version: 0.1.0
            repository: "file://../../zenml-chart"
    